import { createI18n } from 'vue-i18n';

const messages = {
    uz: {
        user_added: "Foydalanuvchi muvaffaqiyatli qo‘shildi!",
        company_added: "Kompaniya muvaffaqiyatli qo‘shildi!",
        customer_added: "Mijoz muvaffaqiyatli qo‘shildi!",
        edit_profile: "Profilni tahrirlash",
        add_picture: "Rasm yuklash uchun bosing",

        settings: 'Sozlamalar',
        cancel: "Bekor qilish",
        notfoundpage: "Kechirasiz, sahifa topilmadi",
        homepage: "Bosh sahifaga qaytish",
        choose: "Tanlang",
        close_menu: "Menyuni yopish",
        selectmode: 'Rejimni tanlash',
        dark: '🌙 Tungi rejim',
        light: '☀️ Yorug‘ rejim',
        selectlanguage: 'Tilni tanlang',
        close: 'Yopish',
        users: 'Foydalanuvchilar',
        companies: 'Kompaniyalar',
        customers: 'Mijozlar',
    },
    en: {
        settings: 'Settings',
        notfoundpage: "Sorry, the page was not found.",
        homepage: "Return to home page",
        cancel: "Cancel",
        choose: "Choose",
        close_menu: "Close sidebar",
        selectmode: 'Select Mode',
        dark: '🌙 Dark Mode',
        light: '☀️ Light Mode',
        selectlanguage: 'Select Language',
        close: 'Close',
        users: 'Users',
        companies: 'Companies',
        customers: 'Customers',
    },
    ru: {
        settings: 'Настройки',
        notfoundpage: "Извините, страница не найдена",
        homepage: "Вернуться на главную страницу",
        cancel: "Отмена",
        choose: "Выбрать",
        close_menu: "Закрыть панель",
        selectmode: 'Выбор режима',
        dark: '🌙 Тёмный режим',
        light: '☀️ Светлый режим',
        selectlanguage: 'Выберите язык',
        close: 'Закрыть',
        users: 'Пользователи',
        companies: 'Компании',
        customers: 'Клиенты',
    },
    kz: {
        settings: 'Параметрлер',
        notfoundpage: "Кешіріңіз, бет табылмады",
        homepage: "Басты бетке оралу",
        cancel: "Болдырмау",
        choose: "Таңдаңыз",
        close_menu: "Панельді жабу",
        selectmode: 'Режимді таңдау',
        dark: '🌙 Қараңғы режим',
        light: '☀️ Жарық режим',
        selectlanguage: 'Тілді таңдаңыз',
        close: 'Жабу',
        users: 'Пайдаланушылар',
        companies: 'Компаниялар',
        customers: 'Клиенттер',
    },
    kk: {
        settings: 'Sazlamalar',
        notfoundpage: "Kechirersiz, bunday bo'lim tabilmadi",
        homepage: "Tiykarg'i bo'limge qaytiw",
        cancel: "Biykarlaw",
        choose: "Tan'lan'",
        close_menu: "Menyudi jabiw",
        selectmode: "Rejimdi tan'law",
        dark: "🌙 Tu'ngi rejim",
        light: "☀️ Ku'ndizgi rejim",
        selectlanguage: "Tildi tan'lan'",
        close: 'Jabiw',
        users: 'Paydalaniwshilar',
        companies: 'Kompaniyalar',
        customers: 'Qariydarlar',
    },
};

const i18n = createI18n({
    legacy: false,
    locale: localStorage.getItem('lang') || 'uz',
    fallbackLocale: 'uz',
    messages,
});

export default i18n;
